## Deliverable 2. Create a Customer Travel Destinations Map.

In [14]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Bredasdorp,ZA,-34.5322,20.0403,52.29,80,96,2.84,overcast clouds
1,1,Uruzgan,AF,32.8333,66.0000,37.06,38,29,3.76,scattered clouds
2,2,Torbay,CA,47.6666,-52.7314,37.58,78,90,10.36,overcast clouds
3,3,Ushuaia,AR,-54.8000,-68.3000,47.86,81,75,14.97,light intensity drizzle
4,4,Sao Filipe,CV,14.8961,-24.4956,76.82,69,57,6.33,broken clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 85

In [6]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)].dropna()
                                                                              #4b^
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
4,4,Sao Filipe,CV,14.8961,-24.4956,76.82,69,57,6.33,broken clouds
5,5,Hobyo,SO,5.3505,48.5268,78.44,70,100,14.41,overcast clouds
7,7,Diebougou,BF,10.9667,-3.2500,74.53,19,12,3.29,few clouds
10,10,Avarua,CK,-21.2078,-159.7750,80.65,89,75,6.91,light rain
11,11,Sao Raimundo Nonato,BR,-9.0153,-42.6994,77.07,62,2,1.74,clear sky
15,15,Busselton,AU,-33.6500,115.3333,73.09,42,0,14.81,clear sky
16,16,Bambous Virieux,MU,-20.3428,57.7575,78.22,78,20,8.05,light rain
17,17,Ahipara,NZ,-35.1667,173.1667,72.01,68,100,8.12,light rain
18,18,Hilo,US,19.7297,-155.0900,80.28,83,90,6.91,mist
23,23,Nueva Loja,EC,0.0847,-76.8828,71.91,98,100,0.74,overcast clouds

In [8]:
# 4a. Determine if there are any empty rows
preferred_cities_df.count()

City_ID                232
City                   232
Country                232
Lat                    232
Lng                    232
Max Temp               232
Humidity               232
Cloudiness             232
Wind Speed             232
Current Description    232
dtype: int64

In [9]:
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
     # # #---added .dropna() when creating preferred_cities_df DataFrame---# # #

In [18]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Sao Filipe,CV,76.82,broken clouds,14.8961,-24.4956,
5,Hobyo,SO,78.44,overcast clouds,5.3505,48.5268,
7,Diebougou,BF,74.53,few clouds,10.9667,-3.2500,
10,Avarua,CK,80.65,light rain,-21.2078,-159.7750,
11,Sao Raimundo Nonato,BR,77.07,clear sky,-9.0153,-42.6994,
15,Busselton,AU,73.09,clear sky,-33.6500,115.3333,
16,Bambous Virieux,MU,78.22,light rain,-20.3428,57.7575,
17,Ahipara,NZ,72.01,light rain,-35.1667,173.1667,
18,Hilo,US,80.28,mist,19.7297,-155.0900,
23,Nueva Loja,EC,71.91,overcast clouds,0.0847,-76.8828,

In [23]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        print(hotel_df.loc[index, "Hotel Name"])
    except(IndexError):
        print("******Hotel not found... skipping.")
    
print("(((((((****complete****)))))))")

Hotel Xaguate
Halane Hotel and Restaurent
Hotel Le Consulat
Paradise Inn
Real Hotel
Observatory Guest House
Casa Tia Villa
Ahipara Holiday Park
Hilo Hawaiian Hotel
Limoncocha Great Hotel
castelo pizzaria
Scoop Guest House
Lorengau Harbourside Hotel
Sea Lounge! Bar, Club & Restaurant
Batemans Bay Marina Resort
Melrose
Hotel Paternopoli
Guest House HESADA
Heritage Park Hotel
People ThankYou
Daiwik Hotels Rameswaram
A Beach Retreat On Casey Key
Casa Rosa Hotel Residence
Isles Sunset Lodge
Tarumã Tropical Hotel
Casa Dora, Bubaque
Hotel Arena Blanca
janelas do mar
asi es
Axim Beach Resort And Spa
HOTEL BOURAQ INDAH PERMAI
Sama Emirate Hotel
Chambres d'hôte "La Trinité"
Iglesia morava renovada
Hospedaje Eco
Haajy Guest House 1
Marriott's Ko Olina Beach Club
Kwepunha Retreat
HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel
Maui Seaside Hotel
Juvinal Martin
Hotel Verano Plaza
Abaco Beach Resort
Villa Enata
Maia's Beach Resort
Shandrani Beachcomber Resort & Spa
Mittagong Motel
Shanti Maurice Resort & Spa
Pousada Porto Praia
Raybow International Hotel
Salinas do Maragogi All Inclusive Resort
Keleti Beach Resort
Bungalow 63
Nusa Island Retreat
فندق يوغسلافيا
Mess keban agung
Hotel Tesoro Los Cabos
******Hotel not found... skipping.
Wembley Park Hotel
Cititel Penang
Akwa Reef Lodge
Vahmoneh Lodge Vanimo
Hotel Bressan
Village das Minas Hotel
هتل گدروشیا
PT PPI Lamongan Tambak C
Hotel y restaurante "El Diamante"
******Hotel not found... skipping.
Lingao Ditai Inn
Taloa Heights
Penginapan Kim
Hotel Juba
Hotel Aconcagua
Mega Hotel, Miri
Pousada Porto De Canoas
Islazul Niquero
Cancha la original
HS Hotsson Smart Acapulco
Ilha Flat Hotel
******Hotel not found... skipping.
Posada Lilia
Hôtel Salama
Screensaver
Circuit House
Will T Place
NASKAR HOUSE .NABAGRAM FULTALA
شهدان. ابوالحجر
Coastline Guest House
Chez Roger
Dream Land
Hotel Playa Star
INN NEW HORIZON
Sheraton Kauai Coconut Beach Resort
Le Monitel
ibis Hermosillo
Foyer ADM
Hospitality Carnarvon
Aipana Plaza Hotel
Le Gîte d’Iracoubo
Hotel Durval
Hotel Ambulu Jember
K2 Lembeh
Aldea del Bazar Hotel and Spa
Oceano
Shelly Bay Resort
Hotel Zaraza
Hotel Vitória
Pousada e Restaurante Cheiro e Sabor
Maitai Lapita Village Huahine
ALETHEIA Appartement Sinnamary
Mini Hotel Central
******Hotel not found... skipping.
Mercure Padang
Quality Suites Vila Velha
Hotel Playa Bonita
Universal Gab Hotel
Uruna Bay Retreat
Radisson Grenada Beach Resort
ZINGARA 76ft Catamaran, full crew-all included
Hotel Albergue de Olinda
Paradise Bay Resort
Guest House Epervier
Hotel del Comahue
Grage Hotel Bengkulu
Hotel Lago da Palma
Dena Hotel
Bora-Bora Pearl Beach Resort & Spa
Corper's Lodge Obonoma
Khách sạn Sài Gòn Bạc Liêu
Rio Xingu Camping
Jambalaya Pousada
Costa Verde Beach Hotel
Rumah mbah Jamah
******Hotel not found... skipping.
Sur Plaza Hotel
Parra Hotel & Suites
Planta Hotel & Residences
Hotel Chik Chik Namibe
Amangalla
BON Hotel Waterfront Richards Bay
Gerasimos Safari Lodge
Agan-Hotel
Hotel "Punta del Cerro"
Hotel Novo Horizonte
Hôtel Le Dronmi
Hotel Porto do Sol
Shenzhen Shanghai Hotel
Blue Ridge Beach Resort
Nile Palace Hotel
Novotel Phuket Resort
Pousada Pau Brasil
Bambuda hotel
Leisure Spring Hotel
OYO 3114 Homestay Dalimo
******Hotel not found... skipping.
******Hotel not found... skipping.
Splendeur de l'équateur
Grand Vilia Hotel
OCHA Office
Auberge Tembina Betaré Oya
Gîte kajeon
Pereybere Hotel & Spa
pondok pesantren mamba'ul 'ulum selo rejo
Hotel Paraiso
Kamaneahn Hotel Inc
Caribbea Bay Hotel
Auberge Relwende
Desert Palms Alice Springs
Hotel San Rafael
Hotel Kou-Bugny
Pousada Guará's
Hotel Plaza Providencia
SPOT ON 64083 Hotel Ganga
Hotel Shekinah
Lakeview Inn Binga
Recanto dos Ferreiras
Minshuku Agaihama
la terrasse
Hotel Jaicós
Welcomhotel By ITC Hotels, Bay Island, Port Blair
Hotel Executivo Palace
Whispering Bamboo Cove Resort
Hotel Narayan Avezika Comfort
Hotel La dorada
Hotel Brasão & Floricultura Bella Flor
Posada Pasito's III, Paso de Patria Ñeembucú
La Case Bambou
Fengshui Residence
Montesino Hotel & Restaurante
Serras Hotel
Kost Pria
******Hotel not found... skipping.
Hotel Santa Mônica
Floresta Amazonica Hotel
Tour Eiffel Hotel Benin
******Hotel not found... skipping.
Hotel H1
P.W.D. Rest House
Sunrise Attitude Hotel
Aviador Hotel Boutique
Waigo Splash Hotel
Delta Sea Mall
Kokopo Beach Bungalow Resort
hotêl doufoulougou
Reserva do Abiaí
Shellharbour Resort & Conference Centre
Atrás de você
Veranda Paul et Virginie Hotel & Spa
HOTEL PLACE YALABA
******Hotel not found... skipping.
IGLESIA EVANGELICA DEL PRINCIPE DE PAZ
Hotels in Lakshadweep Islands
Hotel Citra
Hospedaje madero
ณ ธาตุพนมเพลส Na That Panom Place Hotel
Villa Orphee
******Hotel not found... skipping.
JABIR HOTEL
quinta antigua
CeBlue Villas & Beach Resort
Palace hotel
Beso del Viento
Hoang Yen Canary Hotel
Moon light Furnished Units
El Salvial
Auberge La Place de Jules
JM Lodge
Osprey Beach Hotel
Hannah's Homestay
Sloth Island Nature Resort
La Ode Husein
Reason Inn
(((((((****complete****)))))))

In [26]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Sao Filipe,CV,76.82,broken clouds,14.8961,-24.4956,Hotel Xaguate
5,Hobyo,SO,78.44,overcast clouds,5.3505,48.5268,Halane Hotel and Restaurent
7,Diebougou,BF,74.53,few clouds,10.9667,-3.2500,Hotel Le Consulat
10,Avarua,CK,80.65,light rain,-21.2078,-159.7750,Paradise Inn
11,Sao Raimundo Nonato,BR,77.07,clear sky,-9.0153,-42.6994,Real Hotel
15,Busselton,AU,73.09,clear sky,-33.6500,115.3333,Observatory Guest House
16,Bambous Virieux,MU,78.22,light rain,-20.3428,57.7575,Casa Tia Villa
17,Ahipara,NZ,72.01,light rain,-35.1667,173.1667,Ahipara Holiday Park
18,Hilo,US,80.28,mist,19.7297,-155.0900,Hilo Hawaiian Hotel
23,Nueva Loja,EC,71.91,overcast clouds,0.0847,-76.8828,Limoncocha Great Hotel

In [24]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.isnull().sum()

City                   0
Country                0
Max Temp               0
Current Description    0
Lat                    0
Lng                    0
Hotel Name             0
dtype: int64

In [25]:
hotel_df.count()

City                   232
Country                232
Max Temp               232
Current Description    232
Lat                    232
Lng                    232
Hotel Name             232
dtype: int64

In [27]:
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search/WeatherPy_Vacation.csv"

# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [34]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
# 11a. Add a marker layer for each city to the map. 
# 11b. Display the figure
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df['Max Temp']
fig = gmaps.figure(center=(30.0,31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))